dist: trusty
sudo: required
cache:
  directories:
    - node_modules
language: node_js
addons:
  chrome: stable
  firefox: '62.0.3'

addons:
  apt:
    #sources:
    #  - google-chrome
    #packages:
    #  - google-chrome-stable
    update: true


node_js:
  - 'stable'
before_install:
  - sudo apt-get update -q
  - npm install selenium-standalone@latest -g
  - selenium-standalone install && selenium-standalone start &
  #- npm install -g selenium-webdriver
  - sudo apt-get install -y chromium-chromedriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xvzf geckodriver-v0.23.0-linux64.tar.gz
  - rm geckodriver-v0.23.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo cp geckodriver /usr/local/bin/
  - npm install express --no-save
  - cd back-end
  - npm install
  - cd ..
  - cd selenium-tests
  - npm install
  - cd ..

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3

script:
  - node back-end/bin/www &
  - node selenium-tests/test_homepage_exists.js
