dist: trusty
sudo: required
cache:
  directories:
    - node_modules
language: node_js
addons:
  chrome: stable
  firefox: '62.0.3'

addons:
  apt:
    #sources:
    #  - google-chrome
    #packages:
    #  - google-chrome-stable
    update: true


node_js:
  - 'stable'
before_install:
  - sudo apt-get update -q
  - npm install -g selenium-webdriver
  - chmod +x selenium-webdriver
  - sudo cp selenium-webdriver /usr/local/bin/
  - sudo apt-get install -y chromium-chromedriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xvzf geckodriver-v0.23.0-linux64.tar.gz
  - rm geckodriver-v0.23.0-linux64.tar.gz
  - chmod +x geckodriver
  - sudo cp geckodriver /usr/local/bin/
  - npm install express --no-save

script:
  - node back-end/bin/www &
  - node selenium-tests/test_homepage_exists.js
